services:
  epson2paperless:
    build: .
    container_name: epson2paperless
    network_mode: host
    environment:
      - PRINTER_IP=192.0.2.58
      - SCAN_DEST_NAME=Paperless
      - LOG_LEVEL=info
    volumes:
      - ./scans:/output
    restart: unless-stopped
